import type { SalesAction } from "./sales-types.ts";
import type { Intent } from "../types/turn-analysis.ts";

const NONE: readonly SalesAction[] = [];

/**
 * Complete current-turn intent coverage. The record makes a new TurnAnalysis
 * intent a compile error until its business obligation is decided explicitly.
 */
export const INTENT_ACTION_OBLIGATIONS = {
  greeting: ["ask_course_interest"],
  course_overview: ["answer_course"],
  course_topics: ["answer_topics"],
  course_duration: ["answer_duration"],
  learning_method: ["answer_course"],
  practical_learning: ["answer_course"],
  fee_question: ["answer_fee"],
  gst_question: ["answer_gst"],
  admission_fee_question: ["answer_admission_fee"],
  total_fee_question: ["answer_total_fee"],
  installment_question: ["answer_installment"],
  discount_question: ["answer_fee"],
  scholarship_question: ["answer_support"],
  refund_question: ["answer_support"],
  placement_question: ["answer_placement"],
  job_guarantee_question: ["answer_job_guarantee"],
  salary_question: ["answer_salary"],
  career_question: ["answer_course"],
  internship_question: ["answer_internship"],
  internship_duration: ["answer_internship"],
  internship_paid: ["answer_internship"],
  internship_mode: ["answer_internship"],
  internship_company_choice: ["answer_internship"],
  internship_certificate: ["answer_internship", "answer_certificate"],
  eligibility_question: ["answer_eligibility"],
  qualification_statement: NONE,
  batch_question: ["answer_batch"],
  joining_question: ["answer_joining"],
  class_timing_question: ["answer_class_timing"],
  branch_question: ["answer_branch"],
  location_question: ["answer_location", "send_branch_location"],
  facility_question: ["answer_facility"],
  hostel_question: ["answer_hostel"],
  certificate_question: ["answer_certificate"],
  mentor_support_question: ["answer_support"],
  lms_question: ["answer_support"],
  recorded_class_question: ["answer_support"],
  demo_question: ["answer_demo_availability"],
  demo_acceptance: NONE,
  demo_rejection: ["handle_demo_hesitation"],
  booking_request: NONE,
  booking_date: NONE,
  booking_time: NONE,
  booking_branch: NONE,
  booking_name: NONE,
  booking_contact: NONE,
  brochure_request: ["send_brochure"],
  syllabus_request: ["send_syllabus"],
  testimonial_request: ["send_testimonial"],
  parent_delay: ["handle_parent_objection"],
  competitor_comparison: ["handle_competitor_objection"],
  fee_objection: ["handle_fee_objection"],
  course_switch: NONE,
  not_interested: ["acknowledge_stop_signal"],
  human_request: ["escalate_human_request"],
  other: NONE,
} as const satisfies Record<Intent, readonly SalesAction[]>;
